### ISSUE TITLE
Sega - Dreamcast (2070).dat - Tough Guy (USA, Japan) (Unl)

### ISSUE THREAD

**Issue by Daeymon** [MetalSlug/MAMERedump#6]
For "Tough Guy" in the Dreamcast dat, I'm unable to get a chd that verfies back to the dat.

I'm using a Redump verified version of the cue/bin files and the latest release of chdman. I'm unable to find a gdi file for this game, so stuck just using the cue file.

Could you double check this sha within your dat and if its still fine, could you advise on what I'm doing wrong with creating my chd version?

**Comment by MetalSlug** [comment]
Thanks for the verification. I remember this one.  Because the metadata is included in the checksum, it also makes a difference whether cue or gdi was used. Since I used GDI for all Sega Dreamcast games, I had to create this one myself. Added it under Metadata/Additional GDI Files. I will add a building instruction in the readme. Please report me if there are more mismatches.
